name: EchoBot Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore ./Samples/PublicSamples/EchoBot/src/EchoBot/EchoBot.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore --runtime win-x64 ./Samples/PublicSamples/EchoBot/src/EchoBot/EchoBot.csproj

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Az module
        uses: azure/powershell@v1
        with:
          inlineScript: Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          azPSVersion: latest
          pwsh: true

      - name: Deploy EchoBot
        run: |
          cd ./Samples/PublicSamples/EchoBot
          . .\deploy.ps1 -orgName Modbit7 -Location eastus -RunSetup
          . .\deploy.ps1 -orgName Modbit7 -Location eastus -RunDeployment
